# Generated by Django 5.1.1 on 2024-10-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.BooleanField(choices=[(True, "MALE"), (False, "FEMALE")]),
                ),
                ("age", models.IntegerField()),
                ("prescription_detail", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                ("medicine_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("brand", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("category", models.CharField(max_length=50)),
                ("expiry_date", models.DateField()),
                ("stock_level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("stock_level", models.IntegerField()),
                ("reorder_level", models.IntegerField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharma.medicine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("quantity", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("dosage", models.IntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharma.customer",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharma.medicine",
                    ),
                ),
            ],
        ),
    ]
