# Generated by Django 5.1.1 on 2024-11-21 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharma", "0002_wholesaler_isregistrationcomplete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wholesaler",
            old_name="address",
            new_name="wholesaler_name",
        ),
        migrations.RemoveField(
            model_name="wholesaler",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="wholesaler",
            name="name",
        ),
        migrations.RemoveField(
            model_name="wholesaler",
            name="user",
        ),
        migrations.AddField(
            model_name="wholesaler",
            name="wholesaler_address",
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wholesaler",
            name="wholesaler_contact_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
